management:
#  server:
#    port: 9292
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
#      show-details: always
      show-components: always
  info:
    java:
      enabled: true
    os:
      enabled: true
    git:
      enabled: true
      mode: full
    build:
      enabled: true
    env:
      enabled: true
info:
  app:
    name: hello-actuator
    company: Glenn

logging:
  level:
    hello.controller: debug

server:
  tomcat:
    mbeanregistry:
      enabled: true